### ISSUE TITLE
Change to a Free Software tracker

### ISSUE THREAD

**Issue by christian-momon** [Piwigo/Piwigo#1048]
Previously, the bug tracker used by Piwigo project was a real Free Software.
Now, the official one is Github which is clearly not Free Software.
There is a definite contradiction in using non-free tools for a free project.
This is a very strong barrier for librists who would like to participate in the project.
It would be wonderful if Piwigo returned to free software tools.

**Comment by plegall** [comment]
Hi @christian-momon 

First I invite you to read this forum post https://piwigo.org/forum/viewtopic.php?id=25874

Then to answer more precisely to your question/remark : yes we've lost a bit of freedom by using Github Issues instead of self-hosted Mantis Bug Tracker, but:

- we no longer have to manage the bugtracker, at a hosting level. Less energy spent on this can be spent somewhere else.
- working with automatic links between commit logs and issues is highly practical (for example we write "fixes `#123` ..." in commit log and it automatically link to issue 123 and close it)
- using Github is now the default standard for open source software... and it's not as bad as what your post implies, in my opinion.
- Github Issues works very nicely, I like it much better than Mantis

Moving to Github was a difficult choice but I assume it and I'm happy we did it. We have received much more "small external contributions" than it was possible with our old system.
