### ISSUE TITLE
calls made in http while browsing on https

### ISSUE THREAD

**Issue by vitis586** [Piwigo/Piwigo#1128]
I am using https on my gallery and when I want to generate multiple size images, the batch manager call i.php via http and this request gets blocked. The blocked request shows in the dev console of a browser (Opera, did not show up in Firefox). As a result the thumbnails generation fails with an error "8 photos can not be regenerated".

This issue got discovered by flop25 in this topic https://piwigo.org/forum/viewtopic.php?pid=175220#p175220

**Comment by StevenPolley** [comment]
I can reproduce this exact problem and have figured out a hack to fix it.   This occurs for me because I use piwigo with HTTP, but I have it behind a reverse proxy which handles SSL/TLS termination for external traffic.  

Because the logic in Piwigo at ws.php?format=json&method=pwg.getMissingDerivatives returns absolute URLs, and because Piwigo thinks it's using HTTP, the protocol is returned to my browser as HTTP but really it's HTTPS.  

The fix I did for my instance is to modify gallery/include/functions_url.inc.php
 line 48 http should be change to https, because of  reverse proxy external protocol being HTTPS.  

The long term fix will need to be made in this file, but I'm not a PHP programmer so I can't really contribute more to this.

**Comment by StevenPolley** [comment]
Oh shoot, I didn't see choenig's mention there.  Whoops.  I'm new to this jithub

**Comment by hoedlmoser** [comment]
in case of header X-Forwarded-Host is set, function get_absolute_root_url will not take care of ports.
see https://github.com/Piwigo/Piwigo/blob/master/include/functions_url.inc.php#L50

e.g. for nginx just add to your proxy location:
`proxy_set_header X-Forwarded-Host $http_host;`

see also #681, #982

**Comment by vitis586** [comment]
Thanks, that did the trick for me too!
