### ISSUE TITLE
[11.x] ob_clean(): failed to delete buffer - corrupted downloads

### ISSUE THREAD

**Issue by andydunkel** [Piwigo/Piwigo#1297]
Hi,

I recently updated to version 11.1.0 and noticed that image downloads were corrupted and could not be opened.

I checked the file with a hex editor and found the problem. A PHP notice at the start of the file:

![piwigo_3](https://user-images.githubusercontent.com/355448/105627910-ddaa3b80-5e39-11eb-9a64-a0274c07ac16.jpg)

`Notice ob_clean(): failed to delete buffer. No buffer to delete in action.php on line 224`

I changed the line with an additional check, I am no PHP expert, so the solution might not be good:

![piwigo_4](https://user-images.githubusercontent.com/355448/105627935-0af6e980-5e3a-11eb-9db8-3075a11019ae.jpg)

However image downloads are currently working again. I am not sure if its a problem with Piwigo or my server.

Andy

**Comment by plegall** [comment]
In `i.php` Piwigo does:

```
if (ob_get_length () !== FALSE)
```

before calling `ob_clean()`

**Comment by erAck** [comment]
Fwiw, I left a comment at commit db65aa51d52ec2b4bd00b2f7835770779b19579c

**Comment by vilnus** [comment]
Hello, I have the same problem in a fresh install (piwigo version 12.3.0 - php7.3).
The downloaded file is corrupted (incomplete, I get a .part file) with Firefox (v100.0), but not in Chrome nor Edge).
The problem seems to be solved when I comment ob_clean() in action.php even if I assume that this is not the best way to proceed.
