### ISSUE TITLE
please tell us which PHP versions are supported

### ISSUE THREAD

**Issue by tessus** [Piwigo/Piwigo#1346]
I've been reading the release notes, searched the gh issues, but this info cannot be found anywhere.

Please, tell us which PHP versions are supported by Piwigo.

There are a bunch of issues that state some error when using PHP X. But these issues are always dragged along and there's never a proper resolution that says: PHP X will be supported in release x.y.z of piwigo.

The info in the readme: `PHP 5.3 or greater (7+ recommended)` is kind of useless, since there are issues open for 7.4 and 8.
PHP 5 is EOL, so are 7.0, 7.1, an d 7.2.

Can you please list the proper PHP versions that are supported by each version of Piwigo?

Also, it's strange that Piwigo rather supports PHP versions that are EOL and most of the time has issues with the ones that are actually used by people and providers (hosters).

**Comment by flop25** [comment]
Also, it's strange that Piwigo rather supports PHP versions that are EOL
and most of the time has issues with the ones that are actually used by
people and providers (hosters).
> not strange at all. Shared web hosting company runs php from 5.6 to 7.3
and sometimes 7.4 .
PHP versions are constantly updated, but introduces incompatibility.
The Piwigo team is extremely small compared to the size of the code.
Piwigo has to run a very wide range of php versions.
Everything combined makes that situation.

Piwigo 11 has been designed to check php versions before upgrading so you
know what it means. We will drop some php compatibility in the future to
focus on latest php versions

**Comment by tessus** [comment]
> Shared web hosting company runs php from 5.6 to 7.3

Those are bad companies then. I'm not sure, but do you know what EOL means? This means that these versions do not even receive security patches anymore. Running any of those versions is irresponsible and negligent (on the part of the hosting companies).
And frankly, you waste a lot of time supporting ancient, insecure, unsafe PHP versions. But that's your problem.

Many PHP projects dropped PHP5 support years ago. Just this week I got a notification that another project just dropped everything below 7.2.

Either way, I'm not here to discuss this.

> Piwigo 11 has been designed to check php versions before upgrading

Thanks, this is good to know, but should be mentioned in the release notes.
Furthermore, is it a `> X` check or a `> X and < Y` check?
Also, it certainly wouldn't hurt to mention these versions in the release notes, especially since you already have the check in the code.

**Comment by tessus** [comment]
As a side note. There's been a PR open for 1.5 years that fixes a corruption when using PHP 7.3. #1103
Given that PHP 7.3 is the oldest supported PHP version, it's rather brutal that Piwigo apparently corrupts js output when running this version. So either you have already fixed these issues and left the PR open or using Piwigo with 7.3 is also not safe.

**Comment by Ainz** [comment]
The reason Webhosting companies still support PHP 5.4 to 8 (mine does) is obvious. Money. They have mitigations in place to cover for the most common security issues related to deprecated php execution. I still have sites that are written in code that requires PHP 5.6 to work (NOT Piwigo) and upgrade is slow because one may have to find a new platform entirely for the content. 
I moved to Piwigo when Menalto Gallery ceased its development. I looked for weeks before finding anything similar with a GPL approach, and found Piwigo. 

We see support questions in the Piwigo forums where gallery admins run on PHP 5.6. There are two options here, either Piwigo ups its standards to not support pre PHP 7.2 / 7.3 or the WebHost companies does. If we want Piwigo to take that step we should all prep for a horde of unhappy "5.6"'ers wanting help with upgrades... at least I believe that is a fair risk the forums will be exposed to that.

Ultimately Piwigo probably wants exposure, many sites running Piwigo. That is how resources for additional development are created.

**Comment by tessus** [comment]
@Ainz I also moved to Piwigo from Menalto. I'm very happy with Piwigo.

But I'm using PHP 7.3, since it is the last supported PHP version. I care about my security and I compile all Internet facing binaries myself.  As I mentioned in my previous comment, it looks like that PHP 7.3 has issues. Maybe the PR was just left open.

All I'm saying is that development should go towards the **current** PHP versions and the unsupported ones should be best effort. Currently it's the other way around, which is IMO the wrong approach, because it's one of the reasons why people don't upgrade their PHP.

Btw, many hosters allow multiple php versions. Unless they use PHP as a module, in which case they should probably stop hosting altogether. (H2 requires Apache event MPM. Apache event MPM requires php-fpm.)

**Comment by flop25** [comment]
I disagree: the current effort is to move forward to the newer version of
PHP. What happens is Piwigo has his legacy "burden", a small team and other
issues to tackle (such as keeping the current user base). So the problem is
way more complex than your description.
Finally we all agree, we need to go forward on newer php and as said and
stated in the features of Piwigo 11 (check them again), Piwigo is now ready
to start that turn

**Comment by tessus** [comment]
Ok, thanks.
