### ISSUE TITLE
Missing parameters: pwg_token when adding new users - Piwigo 12.2.0

### ISSUE THREAD

**Issue by Krystian-Szaro-SSA** [Piwigo/Piwigo#1602]
I have on premise Piwigo server
My environment is as follows:
Piwigo 12.2.0
Operating system: Linux
PHP: 7.4.26
MySQL: 5.5.5-10.3.28-MariaDB
Graphics Library: ImageMagick 6.9.12-31

Activated plugin list:
Admin Tools
Batch Downloader
Community
Extended Description
Language Switch
Look_like_gbo2
Show Photo Identifier
Tag Access Management
User Mass Register

The issue is on the Manage users page. When adding a user the admin got Missing parameters: pwg_token. I've found that this occurs on interface in Polish language. With English it doesn't occurs. Please see attached screenshots.

![piwigo_161](https://user-images.githubusercontent.com/82090202/151145496-81675a7c-5306-4411-891c-e8c325753cd5.png)
![piwigo_160](https://user-images.githubusercontent.com/82090202/151145499-3dd8ac4d-4be3-40c5-8a14-b2514948aa9d.png)

**Comment by zszymczyk** [comment]
I have exactly the same problem. Fresh installation and the same thing.

**Comment by blazejstarosta** [comment]
Same problem, fresh installation, getting "Missing parameters: pwg_token" whenever I try to add a new user.

**Comment by pinksnotdead** [comment]
I confirm. With polish language as default its not posible to add, edit or check (tick) a user. In english (UK) its posible. I had to add english package, logout, login in using english. Then everything was ok. But this not good solution.

**Comment by revoltown** [comment]
yes the problem does not look for solved!

**Comment by pysiek634** [comment]
The problem is in translation  (language/pl_PL/admin.lang.php file)
Please remove " or add \ to line  
$lang['Name field must not be empty'] = 'Pole "nazwa" nie może być puste';

eg
$lang['Name field must not be empty'] = 'Pole \"nazwa\" nie może być puste';

**Comment by revoltown** [comment]
Ok, there was " " I removed it and now I can add users. THANK You!Mateusz LamparskiWysłano z urządzenia mobilnego przy pomocy aplikacji Android Mail.
-------- Oryginalna wiadomość --------Od: pysiek634 ***@***.***> Data: 03.04.2022  19:19  (GMT+01:00) Do: Piwigo/Piwigo ***@***.***> DW: revoltown ***@***.***>, Comment ***@***.***> Temat: Re: [Piwigo/Piwigo] Missing parameters: pwg_token when adding new users - Piwigo 12.2.0 (Issue #1602) 

The problem is in translation  (language/pl_PL/admin.lang.php file)

Please remove " or add \ to line

$lang['Name field must not be empty'] = 'Pole "nazwa" nie może być puste';

eg

$lang['Name field must not be empty'] = 'Pole "nazwa" nie może być puste';

**Comment by revoltown** [comment]
There is another issue ...Mateusz LamparskiWysłano z urządzenia mobilnego przy pomocy aplikacji Android Mail.
-------- Oryginalna wiadomość --------Od: pysiek634 ***@***.***> Data: 03.04.2022  19:19  (GMT+01:00) Do: Piwigo/Piwigo ***@***.***> DW: revoltown ***@***.***>, Comment ***@***.***> Temat: Re: [Piwigo/Piwigo] Missing parameters: pwg_token when adding new users - Piwigo 12.2.0 (Issue #1602) 

The problem is in translation  (language/pl_PL/admin.lang.php file)

Please remove " or add \ to line

$lang['Name field must not be empty'] = 'Pole "nazwa" nie może być puste';

eg

$lang['Name field must not be empty'] = 'Pole "nazwa" nie może być puste';

**Comment by revoltown** [comment]
Mateusz LamparskiWysłano z urządzenia mobilnego przy pomocy aplikacji Android Mail.
-------- Oryginalna wiadomość --------Od: pysiek634 ***@***.***> Data: 03.04.2022  19:19  (GMT+01:00) Do: Piwigo/Piwigo ***@***.***> DW: revoltown ***@***.***>, Comment ***@***.***> Temat: Re: [Piwigo/Piwigo] Missing parameters: pwg_token when adding new users - Piwigo 12.2.0 (Issue #1602) 

The problem is in translation  (language/pl_PL/admin.lang.php file)

Please remove " or add \ to line

$lang['Name field must not be empty'] = 'Pole "nazwa" nie może być puste';

eg

$lang['Name field must not be empty'] = 'Pole "nazwa" nie może być puste';

**Comment by revoltown** [comment]
There is another issue , phpmailer is installed on the system...

**Comment by Krystian-Szaro-SSA** [comment]
> There is another issue , phpmailer is installed on the system...
> 
> [https://pasteboard.co/qjmlaOzvryNC.jpg]

Exception.php is not found in directory. See [here](https://github.com/Piwigo/Piwigo/tree/master/include/phpmailer) if you've got these files and owner / rights are okay.

**Comment by revoltown** [comment]
Files are in the right place there is a symbolic link to the gallery from other drive, it is not a problem all is working fine but that piwigo makes only problems..Mateusz LamparskiWysłano z urządzenia mobilnego przy pomocy aplikacji Android Mail.
-------- Oryginalna wiadomość --------Od: Krystian-Szaro-SSA ***@***.***> Data: 04.04.2022  11:26  (GMT+01:00) Do: Piwigo/Piwigo ***@***.***> DW: revoltown ***@***.***>, Comment ***@***.***> Temat: Re: [Piwigo/Piwigo] Missing parameters: pwg_token when adding new users - Piwigo 12.2.0 (Issue #1602) 

There is another issue , phpmailer is installed on the system...
[https://pasteboard.co/qjmlaOzvryNC.jpg]

Exception.php is not found in directory. See here if you've got these files and owner / rights are okay.

**Comment by pysiek634** [comment]
you have probably problems with smtp configuration. If your config will be correct, there are no errors.
However, is pity there are PHP errors.
If you want to display nice errors
add a few lines to include\functions_mail.inc.php
after line use PHPMailer\PHPMailer\PHPMailer;
add
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

require 'include/phpmailer/Exception.php';
require 'include/phpmailer/PHPMailer.php';
require 'include/phpmailer/SMTP.php';

**Comment by revoltown** [comment]
Hi,  i dont realy know whats going one , when i add lines You told now i get :   pastebin.pl https://pastebin.pl/view/95af5344  
            
          
     
      
       
        Dnia 4 kwietnia 2022 13:29 pysiek634 ***@***.***&gt; napisał(a):
       
    
       
         
 you have probably problems with smtp configuration. If your config will be correct, there are no errors.  
However, is pity there are PHP errors.  
If you want to display nice errors  
add a few lines to include\functions_mail.inc.php  
after line use PHPMailer\PHPMailer\PHPMailer;  
add  
use PHPMailer\PHPMailer\SMTP;  
use PHPMailer\PHPMailer\Exception; 
 require &#39;include/phpmailer/Exception.php&#39;;  
require &#39;include/phpmailer/PHPMailer.php&#39;;  
require &#39;include/phpmailer/SMTP.php&#39;;

**Comment by plegall** [comment]
See f6584f3118b289502b9a2deff88be49a2ba9a143 and 5c84eed08506c116b132dd6a620df2ba0488c7e8

**Comment by revoltown** [comment]
I have a problem uploading pics via app more then one 2,3, is ok but when I'm trying upload 20, 30,40 upload is impossible....Mateusz LamparskiWysłano z urządzenia mobilnego przy pomocy aplikacji Android Mail.
-------- Oryginalna wiadomość --------Od: pysiek634 ***@***.***> Data: 04.04.2022  13:29  (GMT+01:00) Do: Piwigo/Piwigo ***@***.***> DW: revoltown ***@***.***>, Comment ***@***.***> Temat: Re: [Piwigo/Piwigo] Missing parameters: pwg_token when adding new users - Piwigo 12.2.0 (Issue #1602) 
you have probably problems with smtp configuration. If your config will be correct, there are no errors.
However, is pity there are PHP errors.
If you want to display nice errors
add a few lines to include\functions_mail.inc.php
after line use PHPMailer\PHPMailer\PHPMailer;
add
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;
require 'include/phpmailer/Exception.php';
require 'include/phpmailer/PHPMailer.php';
require 'include/phpmailer/SMTP.php';

**Comment by revoltown** [comment]
The files are in the place,what right what owner should be there to files or to catalogue ?  
            
          
     
      
       
        Dnia 4 kwietnia 2022 11:26 Krystian-Szaro-SSA ***@***.***&gt; napisał(a):
       
    
       
         
 
 There is another issue , phpmailer is installed on the system... 
 [https://pasteboard.co/qjmlaOzvryNC.jpg] 
 
 Exception.php is not found in directory. See  github.com here  if you&#39;ve got these files and owner / rights are okay.

**Comment by revoltown** [comment]
Sorry I can't see the differences...?Mateusz LamparskiWysłano z urządzenia mobilnego przy pomocy aplikacji Android Mail.
-------- Oryginalna wiadomość --------Od: pysiek634 ***@***.***> Data: 03.04.2022  19:19  (GMT+01:00) Do: Piwigo/Piwigo ***@***.***> DW: revoltown ***@***.***>, Comment ***@***.***> Temat: Re: [Piwigo/Piwigo] Missing parameters: pwg_token when adding new users - Piwigo 12.2.0 (Issue #1602) 

The problem is in translation  (language/pl_PL/admin.lang.php file)

Please remove " or add \ to line

$lang['Name field must not be empty'] = 'Pole "nazwa" nie może być puste';

eg

$lang['Name field must not be empty'] = 'Pole "nazwa" nie może być puste';
