### ISSUE TITLE
strftime deprecated in PHP 8.1

### ISSUE THREAD

**Issue by SanoKriss** [Piwigo/Piwigo#1653]
`Deprecated: Function strftime() is deprecated in / ... /include/smarty/libs/sysplugins/smarty_internal_runtime_codeframe.php on line 48`

[https://www.php.net/manual/en/function.strftime.php](url)

`Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in / ... /include/template.class.php on line 911`

**Comment by Fade78** [comment]
Also had this problem with a fresh install.

**Comment by plegall** [comment]
Fixed with the update of Smarty to version 4.1. See #1693

**Comment by atanas-filipov** [comment]
I run smarty 4.3. Happens every time I clear the generated templates. 
1. Clear the generated templates
2. Load any page (got the errors)
3. Refresh the page, errors are gone, and all is fine

As addition, I have set my php to show all errors and warnings for debuging purposes ( I don't know if it that matters). 

smarty/libs/sysplugins/smarty_internal_runtime_codeframe.php on line <b>48</b>

**Comment by atanas-filipov** [comment]
I run smarty 4.3. Happens when It creates templates.

Clear the generated templates
Load any page (got the errors)
Refresh the page, errors are gone, and all is fine
As addition, I have set my php to show all errors and warnings for debuging purposes ( I don't know if it that matters).

smarty/libs/sysplugins/smarty_internal_runtime_codeframe.php on line 48

It's fixed in the latest 3x Smarty version, but not on the 4.3
