### ISSUE TITLE
URL seo friendly

### ISSUE THREAD

**Issue by zorodimanche** [Piwigo/Piwigo#617]
It is vital important today to have clean URLs for a good regression in search engines:

https://moz.com/blog/15-seo-best-practices-for-structuring-urls
http://httpd.apache.org/docs/2.0/misc/rewriteguide.html

It would be great to integrate it in the next version of piwigo

**Comment by tkuther** [comment]
See https://github.com/Piwigo/Piwigo/blob/master/include/config_default.inc.php.
To sum it up:
```
$conf['category_url_style'] = 'id-name';
$conf['picture_url_style'] = 'id-file';
$conf['original_url_protection'] = 'images';
$conf['derivative_url_style'] = 2;
```

**Comment by Saur0o0n** [comment]
Well.. I have freshly migrated my files from gallery (menalto) and I must say that Piwigo URL construction is more then awkward... (and I would like to use less friendly word). I don't know if it's because of use of PATH_INFO or there are some other reasons, but still - URL in piwigo is ugly. Why?
- no human readable hierarchy of albums in url (you can see them in gallery breadcrumbs but, URL is always pointing to one, top category)
- you will always have "index/category", "index" or "picture" in front of URL
- and finally, when linking to a picture - it's name is before category

So instead of heaving nice, clean URL like this:
**`http://piwigo.org/anniversary/10years_of_piwigo/team_photo.jpeg`**
We have at best (if you enable proper "clean" config)
**`http://piwigo.org/picture/2828-team_photo/category/9292-10years_of_piwigo`**

**Comment by zorodimanche** [comment]
Indeed a work on the rewriting of url is fundamental today to have a good SEO on the search engines and the structure of the urls hurts the eyes.

**Comment by zorodimanche** [comment]
Structure url should be : domainename.com/album/picturename.jpg

**Comment by konservat0r** [comment]
I remember a good theme in the forum gallery3 about SEO http://galleryproject.org/node/110874 Maybe someone can repeat for Piwigo
