### ISSUE TITLE
RSS feed authentication

### ISSUE THREAD

**Issue by CatalinFrancu** [Piwigo/Piwigo#682]
Is it possible to add authentication to `feed.php`? Most of my albums are private, but I would still love for my family to be able to subscribe to the feed. Presently `feed.php` only works as guest, so the feed does not include new private albums.

Thanks, and thanks for Piwigo in general!

**Comment by modus75** [comment]
If you get a link to the feed in piwigo while logged as a user, it will
contain a user key.

**Comment by CatalinFrancu** [comment]
That is not what I am seeing. On 2.8.6, after logging in as two different users, I visit `feed.php` but the feeds only include public albums. 2.9.0 does the same, with some deprecation warnings: _Methods with the same name as their class will not be constructors in a future version of PHP; FeedHtmlField has a deprecated constructor in /.../piwigo/include/feedcreator.class.php on line 275_

Am I doing something wrong?

**Comment by modus75** [comment]
Don't visit directly. From menubar there is a link RSS notification. You
will find there the rss feed link specific to the connected user.

On May 16, 2017 16:57, "Cătălin Frâncu" <notifications@github.com> wrote:

That is not what I am seeing. On 2.8.6, after logging in as two different
users, I visit feed.php but the feeds only include public albums. 2.9.0
does the same, with some deprecation warnings: *Methods with the same name
as their class will not be constructors in a future version of PHP;
FeedHtmlField has a deprecated constructor in
/.../piwigo/include/feedcreator.class.php on line 275*

Am I doing something wrong?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Piwigo/Piwigo/issues/682#issuecomment-301809166>, or mute
the thread

**Comment by CatalinFrancu** [comment]
Ah, beautiful, thanks! I had hidden most of my menus from _Admin  -> Configuration -> Menus,_ so the link was invisible to me. Works as a charm now.

May I suggest that the same user-specific link also be printed in the HTML as a `<link rel="alternate" ...>` tag. Most RSS readers will then be able to subscribe using the homepage directly.
