### ISSUE TITLE
Is there a way to run FTP Synchronization from the CLI?

### ISSUE THREAD

**Issue by mwcz** [Piwigo/Piwigo#818]
I'm looking for a way to have images automatically sync to Piwigo when I upload them to my NAS.  I can mount a directory from the NAS onto the box running Piwigo, but I still have to click Synchronize in the admin interface.

I'd like to trigger Synchronize via either a cronjob or inotify trigger, but I can't seem to find a way to do that.  Perhaps `tools/piwigo_remote.pl` holds the key?

Thanks for any advice!

**Comment by plegall** [comment]
It would be nice to have a CLI for Piwigo, but we don't. There is no "sync" method in Piwigo web API neither. But it doesn't mean you can't find a workaround. See this old forum topic http://piwigo.org/forum/viewtopic.php?pid=110429#p110429

And instead of searching it again in the future, I add it in Piwigo as tools/remote_sync.pl

**Comment by realSpok** [comment]
I have found this, which I will probably be testing soon: https://github.com/pommes-frites/piwigo-scripts.

**Comment by datwildfire** [comment]
Still need that in 2026
