### ISSUE TITLE
Piwigo looks amazing but the website doesn't show it

### ISSUE THREAD

**Issue by macau23** [Piwigo/Piwigo#858]
Piwigo is an incredible piece of modern-looking brilliantly designed software - but.

Without the right plugins installed it looks a little outdated, and the website showcases the software without these plugins.

If Piwigo doesn't receive a stream of new users it will eventually lose traction - and it must not, because you have a great piece of software here!

Show Piwigo in it's full glory with the Bootstrap theme, with endless scrolling and the Carousel photo view!

**Comment by plegall** [comment]
Hi @macau23 

Thank you for this feedback. I fully agree with you: we need to make Piwigo more "visually attractive" because it gives a good first feeling to newcomers. This is why we redesigned Piwigo.org recently. We have more to do as you suggest.

I plan to add more demos on Piwigo.org. Not only one as we have now. On Piwigo.com we have 4 demos to show 4 different themes. Of course, we should feature Bootstrap Darkroom theme by @tkuther (as we do in the homepage illustration). We could even have a customized front page on the demo as on https://oceanopolis.piwigo.com

We should also think about switching to another default theme. Bootstrap Darkroom would be a nice candidate, but unfortunately several plugins are still not compatible with it. I have to work on it.

**Comment by tkuther** [comment]
While I'm a bit proud Bootstrap Darkroom made it as the teaser theme on piwigo.org, I'm not sure if it would fit in as being the new default theme as it stands now. Mainly because a default theme should be an easy to use base for creating child themes. At least that's how Piwigo's current templating works.

Darkroom comes with a ton of jQuery hackeria to make plugins work, it's really huge (in matter of size) due to the shipped components and various sub-themes, its CSS creation is fully based on Sass, it uses Node.js NPM for package management (@flop25 loves it :D) and it has a ton of config options that make it somewhat hard to read the templates (if-else galore)

I'really do think a modernization of Piwigo's default theme and templating would be a healthy thing for the project's future, but I guess that would need some hard change. Being backwards compatible is a good thing for such a huge theme and plugin infrastructure, but there are times in a projects lifespan where breaking changes need to happen in order to move forward. Something like: port the default theme to bootstrap 4 in Piwigo 3.x and live with the fact that 95% of all themes and plugins will be broken at first. Extend the API and javascript client library. Maybe even decouple the frontend and backend so I can install piwigo-js-client in my angular app and use whatever CSS/JS toolkit I like. Okay, I'm going too far, but a modern default theme is overdue. I guess that was Phil's original intention when he worked on Bootstrap Default.
