### ISSUE TITLE
Unexpected Behavior Of Permissions On Creating New Child Album

### ISSUE THREAD

**Issue by Bibo-Joshi** [Piwigo/Piwigo#892]
On my Piwigo installation, I'm having issues with permissions, when creating child albums. Example:

The group "admin" has access permission for the parent album "A". Now, if I create a child album "B" within album A, I'd expect the group "admin" to have access to B. Instead, for both A and B, the admin-group is deleted from the list of permitted groups and all members of the admin-group are listed in the list of permitted users. I have to restore the settings for A and B using the "appley to child-albums" checkbox.

Since group-membership might change, this not a good behaviour.
I'm I doing something wrong/missing some settings or is this ab bug?

Looking forward to an answer,
Bibo

**Comment by flop25** [comment]
Hello
when creating a child album A.1 from a private album A, the permission are not inherited until you explicitly said so though the check-box or the local config

then about your issue, let's me rephrase in order to check I'm understanding correctly 
you are starting your an album A, private, with a group 'Admin' set as a permitted group.
you create a child album (please could you specify exactly how and with whic settings?) A.1
A.1 is private : the permissions are no group allowed, users from the 'admin' group allowed
A is still private : the permissions are no group allowed, users from the 'admin' group allowed

**Comment by Bibo-Joshi** [comment]
Hi, thanks for the quick response.

I just double checked:
A.1 is private : the permissions are no group allowed, users from the 'admin' group allowed
A is still private : _the permissions for group "admin" are indeed allowed_ (Must have overseen this before), users from the 'admin' group allowed. 

I set the permissions for A via the GUI at 'album -> manage -> permissions'. The I go to Album A -> manage child albums -> create child album.

If you say, I have to explicitly set permission inheratance, could you give me a quick guide on how to do this?

**Comment by flop25** [comment]
what do you have in your local configuration?

**Comment by Bibo-Joshi** [comment]
The issue is still there. Is there no solution? o.0

**Comment by Bibo-Joshi** [comment]
I'll close die to inactivity and also because I've since moved away from Piwigo. :)
