### ISSUE TITLE
Included JShrink version issues with PHP 7.3

### ISSUE THREAD

**Issue by tkuther** [Piwigo/Piwigo#951]
The included version of JShrink is over 6 years old and begins to have issues with newer PHP releases.

Users reported an issue where literal PHP deprecated warnings got merged in the the combined js file, causing javascript syntax errors. See https://github.com/tkuther/piwigo-bootstrap-darkroom/issues/185

JShrink should be upgraded to the latest version v1.3.1.

**Comment by tkuther** [comment]
Still true for 2.10

**Comment by tessus** [comment]
Is it possible to add a version matrix somewhere? Pretty please.

**Comment by plegall** [comment]
I'm still wondering about this issue. JShrink 1.3.3 requires PHP 5.6 while Piwigo 2.10 only requires PHP 5.3.

Now, let's take Wordpress as our "lighthouse", since they're certainly leading the CMS industry and they're based on PHP. I see that since version 5.2 (May 2019, 1.5 year ago) Wordpress requires PHP 5.6 (and now recommend PHP 7.4). Maybe it's time for Piwigo to increase its requirement too!

Before doing such a big step (set PHP requirement to version 7 for example), I would like to have #769 implemented.

**Comment by plegall** [comment]
Let's increase the PHP required version to 7.0 for Piwigo 12.

**Comment by plegall** [comment]
#1310
